### PR TITLE
fix sorting of Requirements table

### LINKED ISSUE #81: Status sorting in Requirements table is broken
image

### PR DESCRIPTION
**Pull request by eagr**
*Issue #, if available:*
Fixes #81

*Description of changes:*
Fix table sorting by fixing the `sortComparator` functions

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: www/src/spec.js [hunk 1]
```diff
@@ -80,8 +80,10 @@ export function Requirements({ requirements, showSection }) {
       valueGetter(params) {
         return params.row.section.id;
       },
-      sortComparator(v1, v2, row1, row2) {
-        return row1.row.cmp(row2.row);
```
Comment (camshaft) [inline www/src/spec.js:84]: We should still use the `cmp` function, just update the logic there. It also might be a good idea to precompute the string we use to sort on since this is executed for basically every pair of requirements.

https://github.com/awslabs/duvet/blob/5e5386879c2d0145c5e0564df59ead54147e8e86/www/src/result.js#L75

Comment (eagr) [reply www/src/spec.js:84]: Thanks for the heads-up. Then I realized the source of the problem was actually the `valueGetter`.

File: www/src/spec.js [hunk 2]
```diff
@@ -78,10 +78,10 @@ export function Requirements({ requirements, showSection }) {
       field: "section",
       headerName: "Section",
       valueGetter(params) {
-        return params.row.section.id;
+        return params.row;
       },
-      sortComparator(v1, v2, row1, row2) {
-        return row1.row.cmp(row2.row);
+      sortComparator(v1, v2) {
+        return v2.cmp(v1);
```
Comment (camshaft) [inline www/src/spec.js:84]: Should these be reversed?
```suggestion
        return v1.cmp(v2);
```

Comment (eagr) [reply www/src/spec.js]: Yeah, I was thinking most people would want desc. ordering on the first click since the list was already in asc. order from the get-go. Just realized there's a better way to do it.

**Review by camshaft — APPROVED** [review]
